### ISSUE TITLE
[QUESTION] Is there a way to run a task at a specific time?

### ISSUE THREAD

**Issue by SamiAlsubhi** [dmontagu/fastapi-utils#155]
fastiapi-utils is great and simple to use. I love the repeat_every functionality. However, is there a way to run a task at a specific time?

**Comment by SamiAlsubhi** [comment]
I created this work around that enables running the task at specific time window. any other suggestions?

        task_time = datetime.time(hour=19, minute=30) # run at 7pm
        @app.on_event("startup")
        @repeat_every(seconds=60 * 60)  # 1 hour
        def print_at_specific_time() -> None:
            global task_time
            print('task run')
            current_time = datetime.datetime.now()
            max_bound = current_time + datetime.timedelta(minutes=30)
            min_bound = current_time - datetime.timedelta(minutes=30)
            max_bound = max_bound.time()
            min_bound = min_bound.time()
            current_time = current_time.time()
            
            print('task scheduler attempted to run, max_bound={}, min_bound={}, task time={}'.format(max_bound, min_bound, task_time))
            if max_bound > task_time and min_bound < task_time:
                print('scheduled task ran')
            else:
                print('scheduled task out of operating window')

**Comment by Mause** [comment]
I suggest you look into apscheduler instead, as it's a much more powerful scheduling library
