### ISSUE TITLE
[FEATURE] Make sqlalchemy an optional dependency

### ISSUE THREAD

**Issue by johnthagen** [dmontagu/fastapi-utils#228]
**Is your feature request related to a problem? Please describe.**

We use `fastapi_utils.InferringRouter` on a lot of projects to enable more natural use of type annotations within FastAPI. On some of these projects, there is no database usage at all or even a different database type all together, such as MongoDB.

We'd like to avoid the need of installing `sqlalchemy` (and its dependency `greenlet`) in these situations, which makes the Docker images larger and is one more package we need to track for updates and audit.

**Describe the solution you'd like**

Be able to install `fastapi-utils` in two ways:

```bash
$ pip install fastapi-utils
# This depends only on fastapi and pydantic
```

```bash
$ pip install fastapi[sqlalchemy]
# This additionally installs the extra-requires sqlalchemy
```

**Additional context**

In Poetry, use the `extras` keyword to accomplish this: https://python-poetry.org/docs/pyproject/#extras

Setuptools docs on optional dependencies: https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies

**Comment by yuval9313** [comment]
Hey, It is fixed in one of the [forks](https://github.com/yuval9313/FastApi-RESTful), You are welcome to give it a try

**Comment by flopberry** [comment]
> Hey, It is fixed in one of the [forks](https://github.com/yuval9313/FastApi-RESTful), You are welcome to give it a try

better make pull request for this feature. I'm also want for this feature but i dont want to install fork instead of this package

**Comment by ghandic** [comment]
+1

**Comment by yuval9313** [comment]
Done in version 0.6.0!
