### ISSUE TITLE
[UPDATE] Is this project still supported?

### ISSUE THREAD

**Issue by johnthagen** [dmontagu/fastapi-utils#250]
**Description**

Is this project still supported? I see the @dmontagu is still active on GitHub but this project hasn't received any commits in over a year. Would like to know if this is something that is still appropriate for new projects or if one of the forks should be considered instead.

**Comment by LindezaGrey** [comment]
i would also be interested if there is a fork that is preferrable

**Comment by johnthagen** [comment]
At least one active fork I know of is https://github.com/yuval9313/FastApi-RESTful, but I was hoping to get some kind of official response before migrating away from `fastapi-utils`.

**Comment by takeda** [comment]
Still no response, I think for now I'll just use the fork, thanks @johnthagen

**Comment by jeanlst** [comment]
This is unfortunate, I guess we should all move to the fork from @johnthagen

**Comment by priyanshu-panwar** [comment]
This project seems to be dead now.
You can collaborate here : https://github.com/priyanshu-panwar/fastapi-utilities | This is based on the same project.
https://pypi.org/project/fastapi-utilities/0.1.0/
I am trying to only include the useful features needed.
Please feel free to add stuff to it.

**Comment by takeda** [comment]
@priyanshu-panwar the https://github.com/yuval9313/FastApi-RESTful mentioned 2 years ago seems to be still active (as of writing, last commit was 4 days ago). Why are you creating another project and what makes it better than FastAPI-RESTful?

**Comment by yuval9313** [comment]
I'll be happy to embed what is necessary if missing @priyanshu-panwar I'm still active and soon might take over this project as well (ahm ahm @dmontagu)

**Comment by yuval9313** [comment]
This project will unite with my fork and both packages will be available and co-develop together, so issues here are still relevant,

We appreciate your patience.

Thanks!
