### ISSUE TITLE
Support to SqlAlchemy 2.0

### ISSUE THREAD

**Issue by rafa761** [dmontagu/fastapi-utils#270]
**Description**
Hi there

Thank you for your effort to maintain this project

Is there any plan to support SqlALchemy 2.0?

I'm trying do install, but got the above error

`#0 8.704 ERROR: Cannot install -r requirements.txt (line 12), -r requirements.txt (line 2) and SQLAlchemy==2.0.8 because these package versions have conflicting dependencies.
#0 8.705 
#0 8.705 The conflict is caused by:
#0 8.705     The user requested SQLAlchemy==2.0.8
#0 8.705     fastapi-utils 0.2.1 depends on sqlalchemy<2.0.0 and >=1.3.12
#0 8.705 
#0 8.705 To fix this you could try to:
#0 8.705 1. loosen the range of package versions you've specified
#0 8.705 2. remove package versions to allow pip attempt to solve the dependency conflict
`

**Comment by cdddg** [comment]
@dmontagu Hope to support SQLAlchemy 2.0

**Comment by marselsultanov** [comment]
@dmontagu Up, thanks

**Comment by pavelzw** [comment]
https://github.com/yuval9313/FastApi-RESTful is a more active fork of this repo that already has slqalchemy 2 support since `0.5.0` https://github.com/yuval9313/FastApi-RESTful/pull/202.

**Comment by priyanshu-panwar** [comment]
This project seems to be dead now.
You can collaborate here : https://github.com/priyanshu-panwar/fastapi-utilities | This is based on the same project.
https://pypi.org/project/fastapi-utilities/0.1.0/

**Comment by yuval9313** [comment]
I've maintained control over this project and now version 0.6.0 sqlalchemy 2 is supported!
