### ISSUE TITLE
[BUG] SQLAlchemy is broken in Poetry

### ISSUE THREAD

**Issue by jotradovec** [dmontagu/fastapi-utils#282]
**SQLAlchemy is broken in Poetry**
When running poetry install on toml with fastapi utils, it fails on sqlalchemy dependency because of this https://github.com/python-poetry/poetry/issues/8529

[Errno 36] File name too long: '/home/<username>/.cache/pypoetry/artifacts/7a/10/99/aef84587ad34e485f2229e9f3f022b9670cbddbae9437e86783c9041d9/tmp_6ysy5q6' -> '/home/<username>/.cache/pypoetry/artifacts/7a/10/99/aef84587ad34e485f2229e9f3f022b9670cbddbae9437e86783c9041d9/SQLAlchemy-1.4.50-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl'

**To Reproduce**
1. Having toml with fastapi-utils = "^0.2.1" and no other dependency on SQLAlchemy
2. Run poetry install

**Expected behavior**
Everything is installed without error.

**Environment:**
 - OS: Ubuntu

Note: the problem is for version 1.4.49 and 1.4.50 of the sqlalchemy. 
Workaround: place slqalchemy = <1.4.49 in local toml file

**Comment by yuval9313** [comment]
Fixed in version 0.6.0 in PR #291
